# Generated by Django 3.0.3 on 2020-02-21 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreetCardServices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNameAndIdMapping',
            fields=[
                ('user_name', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
