# Generated by Django 3.0.3 on 2020-02-10 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StreetCardServices', '0002_auto_20200210_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clearanceLevel', models.IntegerField(choices=[(0, 'Level 0'), (1, 'Level 1'), (2, 'Level 2')])),
                ('address', models.CharField(max_length=500)),
                ('serviceProvider', models.TextField(choices=[('FP', 'Food Pantry'), ('DIC', 'Drop-in Centre'), ('SH', 'Shelter Home'), ('SK', 'Soup Kitchen')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
