# Generated by Django 3.0.3 on 2020-02-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreetCardServices', '0003_socialworker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialworker',
            name='clearanceLevel',
            field=models.IntegerField(choices=[('greeter', 'Greeter'), ('caseworker', 'CaseWorker'), ('service_provider_emp', 'Service Provider Employee')]),
        ),
        migrations.AlterField(
            model_name='socialworker',
            name='serviceProvider',
            field=models.TextField(choices=[('FP', 'Food Pantry'), ('DIC', 'Drop-in Centre'), ('SH', 'Shelter Home'), ('SK', 'Soup Kitchen'), ('NA', 'Not Available'), ('OTH', 'Others')]),
        ),
    ]
