# Generated by Django 3.0.3 on 2020-02-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreetCardServices', '0004_auto_20200212_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialworker',
            name='clearanceLevel',
            field=models.TextField(choices=[('greeter', 'Greeter'), ('caseworker', 'CaseWorker'), ('service_provider_emp', 'Service Provider Employee')]),
        ),
    ]
