# Generated by Django 3.0.3 on 2020-02-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreetCardServices', '0005_auto_20200214_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInsurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InformationDate', models.DateField()),
                ('CoveredByHealthInsurance', models.IntegerField(choices=[(0, 'No'), (1, 'Yes'), (8, "Client Doesn't Know"), (9, 'Client Refused'), (99, 'Data Not Collected')])),
                ('Medicaid', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('Medicare', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('SCHIP', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('VAMedicalServices', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('EmployerProvided', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('COBRA', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('PrivatePay', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('StateHealthInsuranceForAdults', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('IndianHealthServices', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('OtherInsurance', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('SpecifySource', models.CharField(max_length=50)),
                ('Reason', models.TextField(choices=[(1, 'Applied;decision pending'), (2, 'Applied;client not eligible'), (3, 'Client did not apply'), (4, 'Insurance type N/A for this client'), (8, "Client Doesn't Know"), (9, 'Client Refused'), (99, 'Data Not Collected')])),
            ],
        ),
        migrations.CreateModel(
            name='NonCashBenefits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InformationDate', models.DateField()),
                ('BenefitsFromAnySource', models.IntegerField(choices=[(0, 'No'), (1, 'Yes'), (8, "Client Doesn't Know"), (9, 'Client Refused'), (99, 'Data Not Collected')])),
                ('SNAP', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('WIC', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('TANFChildCare', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('TANFTransportation', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('OtherTANF', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('OtherSource', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('SpecifySource', models.CharField(max_length=50)),
                ('RentalAssistanceOngoing', models.IntegerField(null=True)),
                ('RentalAssistanceTemp', models.IntegerField(null=True)),
                ('DataCollectionStage', models.IntegerField(null=True)),
            ],
        ),
    ]
