# Generated by Django 3.0.3 on 2020-02-18 07:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StreetCardServices', '0005_auto_20200214_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('personalId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StreetCardServices.Homeless')),
                ('serviceProvider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StreetCardServices.SocialWorker')),
            ],
        ),
    ]
