# Generated by Django 3.0.3 on 2020-02-19 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StreetCardServices', '0006_auto_20200218_0353'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisablingCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InformationDate', models.DateField()),
                ('PHYSICAL_DISABILITY', models.IntegerField(choices=[(0, 'No'), (1, 'Yes'), (8, "Client Doesn't Know"), (9, 'Client Refused'), (99, 'Data Not Collected')], default=None, null=True)),
                ('PHYSICAL_DISABILITY_IMPAIRING', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (8, "Client Doesn't Know"), (9, 'Client Refused'), (99, 'Data Not Collected')], default=None, null=True)),
                ('DEVELOPMENTAL_DISABILITY', models.IntegerField(choices=[(0, 'No'), (1, 'Yes'), (8, "Client Doesn't Know"), (9, 'Client Refused'), (99, 'Data Not Collected')], default=None, null=True)),
                ('DEVELOPMENTAL_DISABILITY_IMPAIRING', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (8, "Client Doesn't Know"), (9, 'Client Refused'), (99, 'Data Not Collected')], default=None, null=True)),
                ('CHRONIC_HEALTH', models.IntegerField(choices=[(0, 'No'), (1, 'Yes'), (8, "Client Doesn't Know"), (9, 'Client Refused'), (99, 'Data Not Collected')], default=None, null=True)),
                ('CHRONIC_HEALTH_IMPAIRING', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (8, "Client Doesn't Know"), (9, 'Client Refused'), (99, 'Data Not Collected')], default=None, null=True)),
                ('HIV_AIDS', models.IntegerField(choices=[(0, 'No'), (1, 'Yes'), (8, "Client Doesn't Know"), (9, 'Client Refused'), (99, 'Data Not Collected')], default=None, null=True)),
                ('HIV_AIDS_IMPAIRING', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (8, "Client Doesn't Know"), (9, 'Client Refused'), (99, 'Data Not Collected')], default=None, null=True)),
                ('MENTAL_HEALTH', models.IntegerField(choices=[(0, 'No'), (1, 'Yes'), (8, "Client Doesn't Know"), (9, 'Client Refused'), (99, 'Data Not Collected')], default=None, null=True)),
                ('MENTAL_HEALTH_IMPAIRING', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (8, "Client Doesn't Know"), (9, 'Client Refused'), (99, 'Data Not Collected')], default=None, null=True)),
                ('SUBSTANCE_ABUSE', models.IntegerField(choices=[(0, 'No'), (1, 'Alcohol'), (2, 'Drug'), (3, 'Both Drug and Alcohol'), (8, "Client Doesn't Know"), (9, 'Client Refused'), (99, 'Data Not Collected')], default=None, null=True)),
                ('SUBSTANCE_ABUSE_IMPAIRING', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (8, "Client Doesn't Know"), (9, 'Client Refused'), (99, 'Data Not Collected')], default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DomesticViolence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InformationDate', models.DateField()),
                ('DomesticViolenceVictim', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('WhenOccurred', models.IntegerField(choices=[(1, 'Past 3 Months'), (2, 'Three to six months ago'), (3, 'Six Months to One year'), (4, 'One year or more'), (8, "Client Doesn't Know"), (9, 'Client Refused'), (99, 'Data Not Collected')])),
                ('CurrentlyFleeing', models.IntegerField(choices=[(0, 'No'), (1, 'Yes'), (8, "Client Doesn't Know"), (9, 'Client Refused'), (99, 'Data Not Collected')])),
            ],
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='ProjectID',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='DisablingCondition',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='EntryDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='ExitDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='Project',
            field=models.IntegerField(choices=[(0, 'HUD:CoC-HomelessPrevention')], null=True),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AddField(
            model_name='domesticviolence',
            name='EnrollmentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DomesticViolence_EnrollmentID', to='StreetCardServices.Enrollment'),
        ),
        migrations.AddField(
            model_name='domesticviolence',
            name='PersonalId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DomesticViolence_PersonalId', to='StreetCardServices.Homeless'),
        ),
        migrations.AddField(
            model_name='disablingcondition',
            name='EnrollmentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DisablingCondition_EnrollmentID', to='StreetCardServices.Enrollment'),
        ),
        migrations.AddField(
            model_name='disablingcondition',
            name='PersonalId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DisablingCondition_PersonalId', to='StreetCardServices.Homeless'),
        ),
    ]
