# Generated by Django 3.0.3 on 2020-02-19 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StreetCardServices', '0010_auto_20200219_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='PersonalId',
        ),
    ]
