# Generated by Django 3.0.3 on 2020-02-19 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StreetCardServices', '0011_remove_enrollment_personalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='PersonalId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Enrollment_PersonalId', to='StreetCardServices.Homeless'),
        ),
    ]
