# Generated by Django 3.0.3 on 2020-02-19 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StreetCardServices', '0012_enrollment_personalid'),
        ('StreetCardServices', '0006_healthinsurance_noncashbenefits'),
    ]

    operations = [
    ]
