# Generated by Django 3.0.3 on 2020-02-19 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StreetCardServices', '0013_merge_20200219_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomeandsources',
            name='PersonalId',
        ),
    ]
