# Generated by Django 3.0.3 on 2020-02-20 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StreetCardServices', '0015_incomeandsources_personalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='noncashbenefits',
            name='EnrollmentID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='NonCashBenefits_EnrollmentID', to='StreetCardServices.Enrollment'),
        ),
        migrations.AddField(
            model_name='noncashbenefits',
            name='PersonalId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='NonCashBenefits_PersonalId', to='StreetCardServices.Homeless'),
        ),
    ]
