# Generated by Django 3.0.3 on 2020-02-20 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StreetCardServices', '0016_auto_20200220_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomeandsources',
            name='EnrollmentID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='IncomeAndSources_EnrollmentID', to='StreetCardServices.Enrollment'),
        ),
    ]
